FROM mcr.microsoft.com/windows/servercore:ltsc2022
WORKDIR /app
COPY . .
EXPOSE 1-65535
EXPOSE 1-65535/udp
RUN reg import tstsrvr.REG

# add procmon
RUN reg add "HKCU\SOFTWARE\Sysinternals\Process Monitor" /v EulaAccepted /t REG_DWORD /d 1
ADD https://live.sysinternals.com/procmon.exe procmon.exe

ENTRYPOINT ["/app/start.bat"]